<!DOCTYPE html>
<html lang="en" dir="ltr">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="robots" content="noindex">
<title>Export: local - AdminerEvo</title>
<link rel="stylesheet" type="text/css" href="?file=default.css&amp;version=4.8.3">
<script src='?file=functions.js&amp;version=4.8.3' nonce="ZWM5NGUwNWRkNDA3MzExNzYyYTFjMTFlOTBmYTczYTY="></script>
<link rel="shortcut icon" type="image/x-icon" href="?file=favicon.ico&amp;version=4.8.3">
<link rel="apple-touch-icon" href="?file=favicon.ico&amp;version=4.8.3">

<body class="ltr nojs">
<script nonce="ZWM5NGUwNWRkNDA3MzExNzYyYTFjMTFlOTBmYTczYTY=">
mixin(document.body, {onkeydown: bodyKeydown, onclick: bodyClick});
document.body.className = document.body.className.replace(/ nojs/, ' js');
var offlineMessage = 'You are offline.';
var thousandsSeparator = ',';
</script>

<div id="help" class="jush-sql jsonly hidden"></div>
<script nonce="ZWM5NGUwNWRkNDA3MzExNzYyYTFjMTFlOTBmYTczYTY=">mixin(qs('#help'), {onmouseover: function () { helpOpen = 1; }, onmouseout: helpMouseout});</script>

<div id="content">
<p id="breadcrumb"><a href=".">MySQL</a> &raquo; <a href='?username=root' accesskey='1' title='Alt+Shift+1'>Local Site: RvX Staging</a> &raquo; <a href="?username=root&amp;db=local">local</a> &raquo; Export
<h2>Export: local</h2>
<div id='ajaxstatus' class='jsonly hidden'></div>

<form action="" method="post">
<table cellspacing="0" class="layout">
<tr><th>Output<td><label><input type='radio' name='output' value='text' checked>open</label><label><input type='radio' name='output' value='file'>save</label><label><input type='radio' name='output' value='gz'>gzip</label>
<tr><th>Format<td><label><input type='radio' name='format' value='sql' checked>SQL</label><label><input type='radio' name='format' value='csv'>CSV,</label><label><input type='radio' name='format' value='csv;'>CSV;</label><label><input type='radio' name='format' value='tsv'>TSV</label>
<tr><th>Database<td><select name='db_style'><option selected><option>USE<option>DROP+CREATE<option>CREATE</select><label><input type='checkbox' name='routines' value='1' checked>Routines</label><label><input type='checkbox' name='events' value='1' checked>Events</label><tr><th>Tables<td><select name='table_style'><option><option selected>DROP+CREATE<option>CREATE</select><label><input type='checkbox' name='auto_increment' value='1'>Auto Increment</label><label><input type='checkbox' name='triggers' value='1' checked>Triggers</label><tr><th>Data<td><select name='data_style'><option><option>TRUNCATE+INSERT<option selected>INSERT<option>INSERT+UPDATE</select></table>
<p><input type="submit" value="Export">
<input type="hidden" name="token" value="379178:737533">

<table cellspacing="0">
<script nonce="ZWM5NGUwNWRkNDA3MzExNzYyYTFjMTFlOTBmYTczYTY=">qsl('table').onclick = dumpClick;</script>
<thead><tr><th style='text-align: left;'><label class='block'><input type='checkbox' id='check-tables' checked>Tables</label><script nonce="ZWM5NGUwNWRkNDA3MzExNzYyYTFjMTFlOTBmYTczYTY=">qs('#check-tables').onclick = partial(formCheck, /^tables\[/);</script><th style='text-align: right;'><label class='block'>Data<input type='checkbox' id='check-data' checked></label><script nonce="ZWM5NGUwNWRkNDA3MzExNzYyYTFjMTFlOTBmYTczYTY=">qs('#check-data').onclick = partial(formCheck, /^data\[/);</script></thead>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_actionscheduler_actions' checked>wp_actionscheduler_actions</label><td align='right'><label class='block'><span id='Rows-wp_actionscheduler_actions'></span><input type='checkbox' name='data[]' value='wp_actionscheduler_actions' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_actionscheduler_claims' checked>wp_actionscheduler_claims</label><td align='right'><label class='block'><span id='Rows-wp_actionscheduler_claims'></span><input type='checkbox' name='data[]' value='wp_actionscheduler_claims' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_actionscheduler_groups' checked>wp_actionscheduler_groups</label><td align='right'><label class='block'><span id='Rows-wp_actionscheduler_groups'></span><input type='checkbox' name='data[]' value='wp_actionscheduler_groups' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_actionscheduler_logs' checked>wp_actionscheduler_logs</label><td align='right'><label class='block'><span id='Rows-wp_actionscheduler_logs'></span><input type='checkbox' name='data[]' value='wp_actionscheduler_logs' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_betterdocs_analytics' checked>wp_betterdocs_analytics</label><td align='right'><label class='block'><span id='Rows-wp_betterdocs_analytics'></span><input type='checkbox' name='data[]' value='wp_betterdocs_analytics' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_betterdocs_search_keyword' checked>wp_betterdocs_search_keyword</label><td align='right'><label class='block'><span id='Rows-wp_betterdocs_search_keyword'></span><input type='checkbox' name='data[]' value='wp_betterdocs_search_keyword' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_betterdocs_search_log' checked>wp_betterdocs_search_log</label><td align='right'><label class='block'><span id='Rows-wp_betterdocs_search_log'></span><input type='checkbox' name='data[]' value='wp_betterdocs_search_log' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_commentmeta' checked>wp_commentmeta</label><td align='right'><label class='block'><span id='Rows-wp_commentmeta'></span><input type='checkbox' name='data[]' value='wp_commentmeta' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_comments' checked>wp_comments</label><td align='right'><label class='block'><span id='Rows-wp_comments'></span><input type='checkbox' name='data[]' value='wp_comments' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_e_events' checked>wp_e_events</label><td align='right'><label class='block'><span id='Rows-wp_e_events'></span><input type='checkbox' name='data[]' value='wp_e_events' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_e_submissions' checked>wp_e_submissions</label><td align='right'><label class='block'><span id='Rows-wp_e_submissions'></span><input type='checkbox' name='data[]' value='wp_e_submissions' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_e_submissions_actions_log' checked>wp_e_submissions_actions_log</label><td align='right'><label class='block'><span id='Rows-wp_e_submissions_actions_log'></span><input type='checkbox' name='data[]' value='wp_e_submissions_actions_log' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_e_submissions_values' checked>wp_e_submissions_values</label><td align='right'><label class='block'><span id='Rows-wp_e_submissions_values'></span><input type='checkbox' name='data[]' value='wp_e_submissions_values' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_eb_form_settings' checked>wp_eb_form_settings</label><td align='right'><label class='block'><span id='Rows-wp_eb_form_settings'></span><input type='checkbox' name='data[]' value='wp_eb_form_settings' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_adjustmentmeta' checked>wp_edd_adjustmentmeta</label><td align='right'><label class='block'><span id='Rows-wp_edd_adjustmentmeta'></span><input type='checkbox' name='data[]' value='wp_edd_adjustmentmeta' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_adjustments' checked>wp_edd_adjustments</label><td align='right'><label class='block'><span id='Rows-wp_edd_adjustments'></span><input type='checkbox' name='data[]' value='wp_edd_adjustments' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_customer_addresses' checked>wp_edd_customer_addresses</label><td align='right'><label class='block'><span id='Rows-wp_edd_customer_addresses'></span><input type='checkbox' name='data[]' value='wp_edd_customer_addresses' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_customer_email_addresses' checked>wp_edd_customer_email_addresses</label><td align='right'><label class='block'><span id='Rows-wp_edd_customer_email_addresses'></span><input type='checkbox' name='data[]' value='wp_edd_customer_email_addresses' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_customermeta' checked>wp_edd_customermeta</label><td align='right'><label class='block'><span id='Rows-wp_edd_customermeta'></span><input type='checkbox' name='data[]' value='wp_edd_customermeta' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_customers' checked>wp_edd_customers</label><td align='right'><label class='block'><span id='Rows-wp_edd_customers'></span><input type='checkbox' name='data[]' value='wp_edd_customers' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_license_activations' checked>wp_edd_license_activations</label><td align='right'><label class='block'><span id='Rows-wp_edd_license_activations'></span><input type='checkbox' name='data[]' value='wp_edd_license_activations' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_licensemeta' checked>wp_edd_licensemeta</label><td align='right'><label class='block'><span id='Rows-wp_edd_licensemeta'></span><input type='checkbox' name='data[]' value='wp_edd_licensemeta' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_licenses' checked>wp_edd_licenses</label><td align='right'><label class='block'><span id='Rows-wp_edd_licenses'></span><input type='checkbox' name='data[]' value='wp_edd_licenses' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_logmeta' checked>wp_edd_logmeta</label><td align='right'><label class='block'><span id='Rows-wp_edd_logmeta'></span><input type='checkbox' name='data[]' value='wp_edd_logmeta' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_logs' checked>wp_edd_logs</label><td align='right'><label class='block'><span id='Rows-wp_edd_logs'></span><input type='checkbox' name='data[]' value='wp_edd_logs' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_logs_api_requestmeta' checked>wp_edd_logs_api_requestmeta</label><td align='right'><label class='block'><span id='Rows-wp_edd_logs_api_requestmeta'></span><input type='checkbox' name='data[]' value='wp_edd_logs_api_requestmeta' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_logs_api_requests' checked>wp_edd_logs_api_requests</label><td align='right'><label class='block'><span id='Rows-wp_edd_logs_api_requests'></span><input type='checkbox' name='data[]' value='wp_edd_logs_api_requests' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_logs_file_downloadmeta' checked>wp_edd_logs_file_downloadmeta</label><td align='right'><label class='block'><span id='Rows-wp_edd_logs_file_downloadmeta'></span><input type='checkbox' name='data[]' value='wp_edd_logs_file_downloadmeta' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_logs_file_downloads' checked>wp_edd_logs_file_downloads</label><td align='right'><label class='block'><span id='Rows-wp_edd_logs_file_downloads'></span><input type='checkbox' name='data[]' value='wp_edd_logs_file_downloads' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_notemeta' checked>wp_edd_notemeta</label><td align='right'><label class='block'><span id='Rows-wp_edd_notemeta'></span><input type='checkbox' name='data[]' value='wp_edd_notemeta' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_notes' checked>wp_edd_notes</label><td align='right'><label class='block'><span id='Rows-wp_edd_notes'></span><input type='checkbox' name='data[]' value='wp_edd_notes' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_notifications' checked>wp_edd_notifications</label><td align='right'><label class='block'><span id='Rows-wp_edd_notifications'></span><input type='checkbox' name='data[]' value='wp_edd_notifications' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_order_addresses' checked>wp_edd_order_addresses</label><td align='right'><label class='block'><span id='Rows-wp_edd_order_addresses'></span><input type='checkbox' name='data[]' value='wp_edd_order_addresses' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_order_adjustmentmeta' checked>wp_edd_order_adjustmentmeta</label><td align='right'><label class='block'><span id='Rows-wp_edd_order_adjustmentmeta'></span><input type='checkbox' name='data[]' value='wp_edd_order_adjustmentmeta' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_order_adjustments' checked>wp_edd_order_adjustments</label><td align='right'><label class='block'><span id='Rows-wp_edd_order_adjustments'></span><input type='checkbox' name='data[]' value='wp_edd_order_adjustments' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_order_itemmeta' checked>wp_edd_order_itemmeta</label><td align='right'><label class='block'><span id='Rows-wp_edd_order_itemmeta'></span><input type='checkbox' name='data[]' value='wp_edd_order_itemmeta' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_order_items' checked>wp_edd_order_items</label><td align='right'><label class='block'><span id='Rows-wp_edd_order_items'></span><input type='checkbox' name='data[]' value='wp_edd_order_items' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_order_transactions' checked>wp_edd_order_transactions</label><td align='right'><label class='block'><span id='Rows-wp_edd_order_transactions'></span><input type='checkbox' name='data[]' value='wp_edd_order_transactions' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_ordermeta' checked>wp_edd_ordermeta</label><td align='right'><label class='block'><span id='Rows-wp_edd_ordermeta'></span><input type='checkbox' name='data[]' value='wp_edd_ordermeta' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_orders' checked>wp_edd_orders</label><td align='right'><label class='block'><span id='Rows-wp_edd_orders'></span><input type='checkbox' name='data[]' value='wp_edd_orders' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_edd_subscriptions' checked>wp_edd_subscriptions</label><td align='right'><label class='block'><span id='Rows-wp_edd_subscriptions'></span><input type='checkbox' name='data[]' value='wp_edd_subscriptions' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_ff_scheduled_actions' checked>wp_ff_scheduled_actions</label><td align='right'><label class='block'><span id='Rows-wp_ff_scheduled_actions'></span><input type='checkbox' name='data[]' value='wp_ff_scheduled_actions' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_fluentform_draft_submissions' checked>wp_fluentform_draft_submissions</label><td align='right'><label class='block'><span id='Rows-wp_fluentform_draft_submissions'></span><input type='checkbox' name='data[]' value='wp_fluentform_draft_submissions' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_fluentform_entry_details' checked>wp_fluentform_entry_details</label><td align='right'><label class='block'><span id='Rows-wp_fluentform_entry_details'></span><input type='checkbox' name='data[]' value='wp_fluentform_entry_details' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_fluentform_form_analytics' checked>wp_fluentform_form_analytics</label><td align='right'><label class='block'><span id='Rows-wp_fluentform_form_analytics'></span><input type='checkbox' name='data[]' value='wp_fluentform_form_analytics' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_fluentform_form_meta' checked>wp_fluentform_form_meta</label><td align='right'><label class='block'><span id='Rows-wp_fluentform_form_meta'></span><input type='checkbox' name='data[]' value='wp_fluentform_form_meta' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_fluentform_forms' checked>wp_fluentform_forms</label><td align='right'><label class='block'><span id='Rows-wp_fluentform_forms'></span><input type='checkbox' name='data[]' value='wp_fluentform_forms' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_fluentform_logs' checked>wp_fluentform_logs</label><td align='right'><label class='block'><span id='Rows-wp_fluentform_logs'></span><input type='checkbox' name='data[]' value='wp_fluentform_logs' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_fluentform_order_items' checked>wp_fluentform_order_items</label><td align='right'><label class='block'><span id='Rows-wp_fluentform_order_items'></span><input type='checkbox' name='data[]' value='wp_fluentform_order_items' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_fluentform_submission_meta' checked>wp_fluentform_submission_meta</label><td align='right'><label class='block'><span id='Rows-wp_fluentform_submission_meta'></span><input type='checkbox' name='data[]' value='wp_fluentform_submission_meta' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_fluentform_submissions' checked>wp_fluentform_submissions</label><td align='right'><label class='block'><span id='Rows-wp_fluentform_submissions'></span><input type='checkbox' name='data[]' value='wp_fluentform_submissions' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_fluentform_subscriptions' checked>wp_fluentform_subscriptions</label><td align='right'><label class='block'><span id='Rows-wp_fluentform_subscriptions'></span><input type='checkbox' name='data[]' value='wp_fluentform_subscriptions' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_fluentform_transactions' checked>wp_fluentform_transactions</label><td align='right'><label class='block'><span id='Rows-wp_fluentform_transactions'></span><input type='checkbox' name='data[]' value='wp_fluentform_transactions' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_links' checked>wp_links</label><td align='right'><label class='block'><span id='Rows-wp_links'></span><input type='checkbox' name='data[]' value='wp_links' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_nextend2_image_storage' checked>wp_nextend2_image_storage</label><td align='right'><label class='block'><span id='Rows-wp_nextend2_image_storage'></span><input type='checkbox' name='data[]' value='wp_nextend2_image_storage' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_nextend2_section_storage' checked>wp_nextend2_section_storage</label><td align='right'><label class='block'><span id='Rows-wp_nextend2_section_storage'></span><input type='checkbox' name='data[]' value='wp_nextend2_section_storage' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_nextend2_smartslider3_generators' checked>wp_nextend2_smartslider3_generators</label><td align='right'><label class='block'><span id='Rows-wp_nextend2_smartslider3_generators'></span><input type='checkbox' name='data[]' value='wp_nextend2_smartslider3_generators' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_nextend2_smartslider3_sliders' checked>wp_nextend2_smartslider3_sliders</label><td align='right'><label class='block'><span id='Rows-wp_nextend2_smartslider3_sliders'></span><input type='checkbox' name='data[]' value='wp_nextend2_smartslider3_sliders' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_nextend2_smartslider3_sliders_xref' checked>wp_nextend2_smartslider3_sliders_xref</label><td align='right'><label class='block'><span id='Rows-wp_nextend2_smartslider3_sliders_xref'></span><input type='checkbox' name='data[]' value='wp_nextend2_smartslider3_sliders_xref' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_nextend2_smartslider3_slides' checked>wp_nextend2_smartslider3_slides</label><td align='right'><label class='block'><span id='Rows-wp_nextend2_smartslider3_slides'></span><input type='checkbox' name='data[]' value='wp_nextend2_smartslider3_slides' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_options' checked>wp_options</label><td align='right'><label class='block'><span id='Rows-wp_options'></span><input type='checkbox' name='data[]' value='wp_options' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_postmeta' checked>wp_postmeta</label><td align='right'><label class='block'><span id='Rows-wp_postmeta'></span><input type='checkbox' name='data[]' value='wp_postmeta' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_posts' checked>wp_posts</label><td align='right'><label class='block'><span id='Rows-wp_posts'></span><input type='checkbox' name='data[]' value='wp_posts' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_revslider_css' checked>wp_revslider_css</label><td align='right'><label class='block'><span id='Rows-wp_revslider_css'></span><input type='checkbox' name='data[]' value='wp_revslider_css' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_revslider_css_bkp' checked>wp_revslider_css_bkp</label><td align='right'><label class='block'><span id='Rows-wp_revslider_css_bkp'></span><input type='checkbox' name='data[]' value='wp_revslider_css_bkp' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_revslider_layer_animations' checked>wp_revslider_layer_animations</label><td align='right'><label class='block'><span id='Rows-wp_revslider_layer_animations'></span><input type='checkbox' name='data[]' value='wp_revslider_layer_animations' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_revslider_layer_animations_bkp' checked>wp_revslider_layer_animations_bkp</label><td align='right'><label class='block'><span id='Rows-wp_revslider_layer_animations_bkp'></span><input type='checkbox' name='data[]' value='wp_revslider_layer_animations_bkp' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_revslider_navigations' checked>wp_revslider_navigations</label><td align='right'><label class='block'><span id='Rows-wp_revslider_navigations'></span><input type='checkbox' name='data[]' value='wp_revslider_navigations' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_revslider_navigations_bkp' checked>wp_revslider_navigations_bkp</label><td align='right'><label class='block'><span id='Rows-wp_revslider_navigations_bkp'></span><input type='checkbox' name='data[]' value='wp_revslider_navigations_bkp' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_revslider_sliders' checked>wp_revslider_sliders</label><td align='right'><label class='block'><span id='Rows-wp_revslider_sliders'></span><input type='checkbox' name='data[]' value='wp_revslider_sliders' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_revslider_sliders_bkp' checked>wp_revslider_sliders_bkp</label><td align='right'><label class='block'><span id='Rows-wp_revslider_sliders_bkp'></span><input type='checkbox' name='data[]' value='wp_revslider_sliders_bkp' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_revslider_slides' checked>wp_revslider_slides</label><td align='right'><label class='block'><span id='Rows-wp_revslider_slides'></span><input type='checkbox' name='data[]' value='wp_revslider_slides' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_revslider_slides_bkp' checked>wp_revslider_slides_bkp</label><td align='right'><label class='block'><span id='Rows-wp_revslider_slides_bkp'></span><input type='checkbox' name='data[]' value='wp_revslider_slides_bkp' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_revslider_static_slides' checked>wp_revslider_static_slides</label><td align='right'><label class='block'><span id='Rows-wp_revslider_static_slides'></span><input type='checkbox' name='data[]' value='wp_revslider_static_slides' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_revslider_static_slides_bkp' checked>wp_revslider_static_slides_bkp</label><td align='right'><label class='block'><span id='Rows-wp_revslider_static_slides_bkp'></span><input type='checkbox' name='data[]' value='wp_revslider_static_slides_bkp' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_term_relationships' checked>wp_term_relationships</label><td align='right'><label class='block'><span id='Rows-wp_term_relationships'></span><input type='checkbox' name='data[]' value='wp_term_relationships' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_term_taxonomy' checked>wp_term_taxonomy</label><td align='right'><label class='block'><span id='Rows-wp_term_taxonomy'></span><input type='checkbox' name='data[]' value='wp_term_taxonomy' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_termmeta' checked>wp_termmeta</label><td align='right'><label class='block'><span id='Rows-wp_termmeta'></span><input type='checkbox' name='data[]' value='wp_termmeta' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_terms' checked>wp_terms</label><td align='right'><label class='block'><span id='Rows-wp_terms'></span><input type='checkbox' name='data[]' value='wp_terms' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_usermeta' checked>wp_usermeta</label><td align='right'><label class='block'><span id='Rows-wp_usermeta'></span><input type='checkbox' name='data[]' value='wp_usermeta' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_users' checked>wp_users</label><td align='right'><label class='block'><span id='Rows-wp_users'></span><input type='checkbox' name='data[]' value='wp_users' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wpforms_logs' checked>wp_wpforms_logs</label><td align='right'><label class='block'><span id='Rows-wp_wpforms_logs'></span><input type='checkbox' name='data[]' value='wp_wpforms_logs' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wpforms_payment_meta' checked>wp_wpforms_payment_meta</label><td align='right'><label class='block'><span id='Rows-wp_wpforms_payment_meta'></span><input type='checkbox' name='data[]' value='wp_wpforms_payment_meta' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wpforms_payments' checked>wp_wpforms_payments</label><td align='right'><label class='block'><span id='Rows-wp_wpforms_payments'></span><input type='checkbox' name='data[]' value='wp_wpforms_payments' checked></label>
<tr><td><label class='block'><input type='checkbox' name='tables[]' value='wp_wpforms_tasks_meta' checked>wp_wpforms_tasks_meta</label><td align='right'><label class='block'><span id='Rows-wp_wpforms_tasks_meta'></span><input type='checkbox' name='data[]' value='wp_wpforms_tasks_meta' checked></label>
<script nonce="ZWM5NGUwNWRkNDA3MzExNzYyYTFjMTFlOTBmYTczYTY=">ajaxSetHtml('?username=root&db=local&script=db');</script>
</table>
</form>
<p><a href='?username=root&amp;db=local&amp;dump=wp%25'>wp</a></div>

<form action='' method='post'>
<div id='lang'>Language: <select name='lang'><option value="en" selected>English<option value="ar">العربية<option value="bg">Български<option value="bn">বাংলা<option value="bs">Bosanski<option value="ca">Català<option value="cs">Čeština<option value="da">Dansk<option value="de">Deutsch<option value="el">Ελληνικά<option value="es">Español<option value="et">Eesti<option value="fa">فارسی<option value="fi">Suomi<option value="fr">Français<option value="gl">Galego<option value="he">עברית<option value="hu">Magyar<option value="id">Bahasa Indonesia<option value="it">Italiano<option value="ja">日本語<option value="ka">ქართული<option value="ko">한국어<option value="lv">Latviešu<option value="lt">Lietuvių<option value="ms">Bahasa Melayu<option value="nl">Nederlands<option value="no">Norsk<option value="pl">Polski<option value="pt">Português<option value="pt-br">Português (Brazil)<option value="ro">Limba Română<option value="ru">Русский<option value="sk">Slovenčina<option value="sl">Slovenski<option value="sr">Српски<option value="sv">Svenska<option value="ta">த‌மிழ்<option value="th">ภาษาไทย<option value="tr">Türkçe<option value="uk">Українська<option value="vi">Tiếng Việt<option value="zh">简体中文<option value="zh-tw">繁體中文</select><script nonce="ZWM5NGUwNWRkNDA3MzExNzYyYTFjMTFlOTBmYTczYTY=">qsl('select').onchange = function () { this.form.submit(); };</script> <input type='submit' value='Use' class='hidden'>
<input type='hidden' name='token' value='599286:503073'>
</div>
</form>
<form action="" method="post">
<p class="logout">
<input type="submit" name="logout" value="Logout" id="logout">
<input type="hidden" name="token" value="379178:737533">
</p>
</form>
<div id="menu">
<h1>
<a href='https://www.adminerevo.org/' target="_blank" rel="noreferrer noopener" id='h1'>AdminerEvo</a> <span class="version">4.8.3</span>
</h1>
<script src='?file=jush.js&amp;version=4.8.3' nonce="ZWM5NGUwNWRkNDA3MzExNzYyYTFjMTFlOTBmYTczYTY="></script>
<script nonce="ZWM5NGUwNWRkNDA3MzExNzYyYTFjMTFlOTBmYTczYTY=">
var jushLinks = { sql: [ '?username=root&db=local&table=$&', /\b(wp_actionscheduler_actions|wp_actionscheduler_claims|wp_actionscheduler_groups|wp_actionscheduler_logs|wp_betterdocs_analytics|wp_betterdocs_search_keyword|wp_betterdocs_search_log|wp_commentmeta|wp_comments|wp_e_events|wp_e_submissions|wp_e_submissions_actions_log|wp_e_submissions_values|wp_eb_form_settings|wp_edd_adjustmentmeta|wp_edd_adjustments|wp_edd_customer_addresses|wp_edd_customer_email_addresses|wp_edd_customermeta|wp_edd_customers|wp_edd_license_activations|wp_edd_licensemeta|wp_edd_licenses|wp_edd_logmeta|wp_edd_logs|wp_edd_logs_api_requestmeta|wp_edd_logs_api_requests|wp_edd_logs_file_downloadmeta|wp_edd_logs_file_downloads|wp_edd_notemeta|wp_edd_notes|wp_edd_notifications|wp_edd_order_addresses|wp_edd_order_adjustmentmeta|wp_edd_order_adjustments|wp_edd_order_itemmeta|wp_edd_order_items|wp_edd_order_transactions|wp_edd_ordermeta|wp_edd_orders|wp_edd_subscriptions|wp_ff_scheduled_actions|wp_fluentform_draft_submissions|wp_fluentform_entry_details|wp_fluentform_form_analytics|wp_fluentform_form_meta|wp_fluentform_forms|wp_fluentform_logs|wp_fluentform_order_items|wp_fluentform_submission_meta|wp_fluentform_submissions|wp_fluentform_subscriptions|wp_fluentform_transactions|wp_links|wp_nextend2_image_storage|wp_nextend2_section_storage|wp_nextend2_smartslider3_generators|wp_nextend2_smartslider3_sliders|wp_nextend2_smartslider3_sliders_xref|wp_nextend2_smartslider3_slides|wp_options|wp_postmeta|wp_posts|wp_revslider_css|wp_revslider_css_bkp|wp_revslider_layer_animations|wp_revslider_layer_animations_bkp|wp_revslider_navigations|wp_revslider_navigations_bkp|wp_revslider_sliders|wp_revslider_sliders_bkp|wp_revslider_slides|wp_revslider_slides_bkp|wp_revslider_static_slides|wp_revslider_static_slides_bkp|wp_term_relationships|wp_term_taxonomy|wp_termmeta|wp_terms|wp_usermeta|wp_users|wp_wpforms_logs|wp_wpforms_payment_meta|wp_wpforms_payments|wp_wpforms_tasks_meta)\b/g ] };
jushLinks.bac = jushLinks.sql;
jushLinks.bra = jushLinks.sql;
jushLinks.sqlite_quo = jushLinks.sql;
jushLinks.mssql_bra = jushLinks.sql;
bodyLoad('8.0');
</script>
<form action="">
<table id='dbs'><tr><td width=1><input type="hidden" name="username" value="root"><label title='database' for='menu_db'>DB</label>:</td><td><select name='db' id='menu_db'><option value=""><option>information_schema<option selected>local<option>mysql<option>performance_schema<option>sys</select><script nonce="ZWM5NGUwNWRkNDA3MzExNzYyYTFjMTFlOTBmYTczYTY=">mixin(qsl('select'), {onmousedown: dbMouseDown, onchange: dbChange});</script>
</td></tr><tr class='hidden'><td colspan=2><input type='submit' value='Use'></td></tr>
</table><input type='hidden' name='dump' value=''><p class='links'><a href='?username=root&amp;db=local&amp;sql='>SQL command</a><span class='separator'>|</span><a href='?username=root&amp;db=local&amp;import='>Import</a><span class='separator'>|</span><a href='?username=root&amp;db=local&amp;dump=' id='dump' class='active '>Export</a></p><p class='links'><a href="?username=root&amp;db=local&amp;create=">Create table</a></p><ul id='tables'><script nonce="ZWM5NGUwNWRkNDA3MzExNzYyYTFjMTFlOTBmYTczYTY=">mixin(qs('#tables'), {onmouseover: menuOver, onmouseout: menuOut});</script>
<li><a href="?username=root&amp;db=local&amp;select=wp_actionscheduler_actions" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_actionscheduler_actions" class='structure' title='Show structure'>wp_actionscheduler_actions</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_actionscheduler_claims" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_actionscheduler_claims" class='structure' title='Show structure'>wp_actionscheduler_claims</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_actionscheduler_groups" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_actionscheduler_groups" class='structure' title='Show structure'>wp_actionscheduler_groups</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_actionscheduler_logs" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_actionscheduler_logs" class='structure' title='Show structure'>wp_actionscheduler_logs</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_betterdocs_analytics" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_betterdocs_analytics" class='structure' title='Show structure'>wp_betterdocs_analytics</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_betterdocs_search_keyword" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_betterdocs_search_keyword" class='structure' title='Show structure'>wp_betterdocs_search_keyword</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_betterdocs_search_log" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_betterdocs_search_log" class='structure' title='Show structure'>wp_betterdocs_search_log</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_commentmeta" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_commentmeta" class='structure' title='Show structure'>wp_commentmeta</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_comments" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_comments" class='structure' title='Show structure'>wp_comments</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_e_events" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_e_events" class='structure' title='Show structure'>wp_e_events</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_e_submissions" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_e_submissions" class='structure' title='Show structure'>wp_e_submissions</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_e_submissions_actions_log" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_e_submissions_actions_log" class='structure' title='Show structure'>wp_e_submissions_actions_log</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_e_submissions_values" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_e_submissions_values" class='structure' title='Show structure'>wp_e_submissions_values</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_eb_form_settings" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_eb_form_settings" class='structure' title='Show structure'>wp_eb_form_settings</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_adjustmentmeta" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_adjustmentmeta" class='structure' title='Show structure'>wp_edd_adjustmentmeta</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_adjustments" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_adjustments" class='structure' title='Show structure'>wp_edd_adjustments</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_customer_addresses" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_customer_addresses" class='structure' title='Show structure'>wp_edd_customer_addresses</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_customer_email_addresses" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_customer_email_addresses" class='structure' title='Show structure'>wp_edd_customer_email_addresses</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_customermeta" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_customermeta" class='structure' title='Show structure'>wp_edd_customermeta</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_customers" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_customers" class='structure' title='Show structure'>wp_edd_customers</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_license_activations" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_license_activations" class='structure' title='Show structure'>wp_edd_license_activations</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_licensemeta" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_licensemeta" class='structure' title='Show structure'>wp_edd_licensemeta</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_licenses" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_licenses" class='structure' title='Show structure'>wp_edd_licenses</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_logmeta" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_logmeta" class='structure' title='Show structure'>wp_edd_logmeta</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_logs" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_logs" class='structure' title='Show structure'>wp_edd_logs</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_logs_api_requestmeta" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_logs_api_requestmeta" class='structure' title='Show structure'>wp_edd_logs_api_requestmeta</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_logs_api_requests" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_logs_api_requests" class='structure' title='Show structure'>wp_edd_logs_api_requests</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_logs_file_downloadmeta" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_logs_file_downloadmeta" class='structure' title='Show structure'>wp_edd_logs_file_downloadmeta</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_logs_file_downloads" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_logs_file_downloads" class='structure' title='Show structure'>wp_edd_logs_file_downloads</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_notemeta" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_notemeta" class='structure' title='Show structure'>wp_edd_notemeta</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_notes" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_notes" class='structure' title='Show structure'>wp_edd_notes</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_notifications" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_notifications" class='structure' title='Show structure'>wp_edd_notifications</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_order_addresses" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_order_addresses" class='structure' title='Show structure'>wp_edd_order_addresses</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_order_adjustmentmeta" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_order_adjustmentmeta" class='structure' title='Show structure'>wp_edd_order_adjustmentmeta</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_order_adjustments" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_order_adjustments" class='structure' title='Show structure'>wp_edd_order_adjustments</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_order_itemmeta" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_order_itemmeta" class='structure' title='Show structure'>wp_edd_order_itemmeta</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_order_items" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_order_items" class='structure' title='Show structure'>wp_edd_order_items</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_order_transactions" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_order_transactions" class='structure' title='Show structure'>wp_edd_order_transactions</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_ordermeta" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_ordermeta" class='structure' title='Show structure'>wp_edd_ordermeta</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_orders" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_orders" class='structure' title='Show structure'>wp_edd_orders</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_edd_subscriptions" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_edd_subscriptions" class='structure' title='Show structure'>wp_edd_subscriptions</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_ff_scheduled_actions" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_ff_scheduled_actions" class='structure' title='Show structure'>wp_ff_scheduled_actions</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_fluentform_draft_submissions" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_fluentform_draft_submissions" class='structure' title='Show structure'>wp_fluentform_draft_submissions</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_fluentform_entry_details" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_fluentform_entry_details" class='structure' title='Show structure'>wp_fluentform_entry_details</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_fluentform_form_analytics" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_fluentform_form_analytics" class='structure' title='Show structure'>wp_fluentform_form_analytics</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_fluentform_form_meta" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_fluentform_form_meta" class='structure' title='Show structure'>wp_fluentform_form_meta</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_fluentform_forms" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_fluentform_forms" class='structure' title='Show structure'>wp_fluentform_forms</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_fluentform_logs" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_fluentform_logs" class='structure' title='Show structure'>wp_fluentform_logs</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_fluentform_order_items" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_fluentform_order_items" class='structure' title='Show structure'>wp_fluentform_order_items</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_fluentform_submission_meta" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_fluentform_submission_meta" class='structure' title='Show structure'>wp_fluentform_submission_meta</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_fluentform_submissions" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_fluentform_submissions" class='structure' title='Show structure'>wp_fluentform_submissions</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_fluentform_subscriptions" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_fluentform_subscriptions" class='structure' title='Show structure'>wp_fluentform_subscriptions</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_fluentform_transactions" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_fluentform_transactions" class='structure' title='Show structure'>wp_fluentform_transactions</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_links" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_links" class='structure' title='Show structure'>wp_links</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_nextend2_image_storage" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_nextend2_image_storage" class='structure' title='Show structure'>wp_nextend2_image_storage</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_nextend2_section_storage" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_nextend2_section_storage" class='structure' title='Show structure'>wp_nextend2_section_storage</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_nextend2_smartslider3_generators" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_nextend2_smartslider3_generators" class='structure' title='Show structure'>wp_nextend2_smartslider3_generators</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_nextend2_smartslider3_sliders" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_nextend2_smartslider3_sliders" class='structure' title='Show structure'>wp_nextend2_smartslider3_sliders</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_nextend2_smartslider3_sliders_xref" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_nextend2_smartslider3_sliders_xref" class='structure' title='Show structure'>wp_nextend2_smartslider3_sliders_xref</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_nextend2_smartslider3_slides" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_nextend2_smartslider3_slides" class='structure' title='Show structure'>wp_nextend2_smartslider3_slides</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_options" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_options" class='structure' title='Show structure'>wp_options</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_postmeta" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_postmeta" class='structure' title='Show structure'>wp_postmeta</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_posts" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_posts" class='structure' title='Show structure'>wp_posts</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_revslider_css" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_revslider_css" class='structure' title='Show structure'>wp_revslider_css</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_revslider_css_bkp" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_revslider_css_bkp" class='structure' title='Show structure'>wp_revslider_css_bkp</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_revslider_layer_animations" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_revslider_layer_animations" class='structure' title='Show structure'>wp_revslider_layer_animations</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_revslider_layer_animations_bkp" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_revslider_layer_animations_bkp" class='structure' title='Show structure'>wp_revslider_layer_animations_bkp</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_revslider_navigations" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_revslider_navigations" class='structure' title='Show structure'>wp_revslider_navigations</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_revslider_navigations_bkp" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_revslider_navigations_bkp" class='structure' title='Show structure'>wp_revslider_navigations_bkp</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_revslider_sliders" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_revslider_sliders" class='structure' title='Show structure'>wp_revslider_sliders</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_revslider_sliders_bkp" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_revslider_sliders_bkp" class='structure' title='Show structure'>wp_revslider_sliders_bkp</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_revslider_slides" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_revslider_slides" class='structure' title='Show structure'>wp_revslider_slides</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_revslider_slides_bkp" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_revslider_slides_bkp" class='structure' title='Show structure'>wp_revslider_slides_bkp</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_revslider_static_slides" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_revslider_static_slides" class='structure' title='Show structure'>wp_revslider_static_slides</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_revslider_static_slides_bkp" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_revslider_static_slides_bkp" class='structure' title='Show structure'>wp_revslider_static_slides_bkp</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_term_relationships" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_term_relationships" class='structure' title='Show structure'>wp_term_relationships</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_term_taxonomy" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_term_taxonomy" class='structure' title='Show structure'>wp_term_taxonomy</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_termmeta" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_termmeta" class='structure' title='Show structure'>wp_termmeta</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_terms" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_terms" class='structure' title='Show structure'>wp_terms</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_usermeta" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_usermeta" class='structure' title='Show structure'>wp_usermeta</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_users" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_users" class='structure' title='Show structure'>wp_users</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_wpforms_logs" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_wpforms_logs" class='structure' title='Show structure'>wp_wpforms_logs</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_wpforms_payment_meta" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_wpforms_payment_meta" class='structure' title='Show structure'>wp_wpforms_payment_meta</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_wpforms_payments" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_wpforms_payments" class='structure' title='Show structure'>wp_wpforms_payments</a>
<li><a href="?username=root&amp;db=local&amp;select=wp_wpforms_tasks_meta" class='select' title='Select data'>select</a> <a href="?username=root&amp;db=local&amp;table=wp_wpforms_tasks_meta" class='structure' title='Show structure'>wp_wpforms_tasks_meta</a>
</ul>
</div>
<script nonce="ZWM5NGUwNWRkNDA3MzExNzYyYTFjMTFlOTBmYTczYTY=">setupSubmitHighlight(document);</script>
<script nonce="ZWM5NGUwNWRkNDA3MzExNzYyYTFjMTFlOTBmYTczYTY=">setupCopyToClipboard(document);</script>
</body>
</html>